name: Security Scan - Weather App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-complete-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t weather-app:latest .

    - name: Run Trivy vulnerability scanner (JSON)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        format: 'json'
        output: 'trivy-results.json'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        vuln-type: 'os,library'

    - name: Run Trivy vulnerability scanner (HTML)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        format: 'template'
        template: '@contrib/html.tpl'
        output: 'trivy-results.html'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        vuln-type: 'os,library'

    - name: Upload JSON report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-json
        path: trivy-results.json

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-html
        path: trivy-results.html
