name: Security Scan - Weather App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-complete-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t weather-app:latest .


    - name: Vulnerabilities Scan
      run: |
        IMAGE_NAME="weather-app:latest"
        # Escaneo JSON
        trivy image --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --vuln-type os,library \
          --format json --output trivy-results.json $IMAGE_NAME
        # Escaneo HTML
        trivy image --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --vuln-type os,library \
          --format template --template "@contrib/html.tpl" --output trivy-results.html $IMAGE_NAME

    - name: Upload JSON report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-json
        path: trivy-results.json

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report-html
        path: trivy-results.html
