name: Security Scan - Weather App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-complete-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t weather-app:latest .

    - name: "🔍 Vulnerabilities Scan"
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        format: 'table'
        exit-code: '0'
        scanners: 'vuln'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        vuln-type: 'os,library'
        output: 'trivy-results.sarif'          
          
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'          
