name: Security Scan Completo - Weather App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  comprehensive-security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. ESCANEO COMPLETO DEL REPOSITORIO
    - name: "📁 Escaneo del Repositorio Completo"
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

    # 2. ESCANEO DE SECRETOS Y CREDENCIALES
    - name: "🔐 Escaneo de Secretos"
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        scanners: 'secret'
        format: 'table'
        exit-code: '1'

    # 3. ESCANEO DE CONFIGURACIONES (IaC)
    - name: "⚙️ Escaneo de Configuraciones"
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'

    # 4. CONSTRUCCIÓN DE LA IMAGEN DOCKER
    - name: "🐳 Build Docker Image"
      run: docker build -t weather-app:latest .

    # 5. ESCANEO COMPLETO DE LA IMAGEN DOCKER
    - name: "🔍 Escaneo Docker - Vulnerabilidades"
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        format: 'table'
        exit-code: '0'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        vuln-type: 'os,library'

    # 6. ESCANEO DE SECRETOS EN LA IMAGEN
    - name: "🔐 Escaneo Docker - Secretos"
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        scanners: 'secret'
        format: 'table'
        exit-code: '1'

    # 7. ESCANEO DE CONFIGURACIONES EN LA IMAGEN
    - name: "⚙️ Escaneo Docker - Configuraciones"
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        scanners: 'config'
        format: 'table'
        exit-code: '0'

    # 8. ESCANEO DE LICENCIAS
    - name: "📄 Escaneo de Licencias"
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'weather-app:latest'
        scanners: 'license'
        format: 'table'
        exit-code: '0'

    # 9. RESUMEN FINAL
    - name: "📋 Resumen del Escaneo"
      run: |
        echo "==================================="
        echo "🎯 ESCANEO COMPLETO FINALIZADO"
        echo "==================================="
        echo "✅ Repositorio escaneado"
        echo "🔐 Secretos verificados"  
        echo "⚙️ Configuraciones analizadas"
        echo "🐳 Imagen Docker escaneada"
        echo "📄 Licencias verificadas"
        echo "==================================="
